### ISSUE TITLE
Update dependabot configuration to update 2.x branch

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#157]
When the current `main` branch is migrated to branch `2.x` (see #87 ), we want to receive dependabot updates on this branch.

- [x] Prereq: the current `main` must be migrated to a new brauch `2.x`
- [x] Dependency configuration:
  - [x] `io.quarkus.platform`-dependencies must not be `>= 3.0.0`
    ```yaml
    ignore:
      ...
      - dependency-name: "io.quarkus:quarkus-bom"
        versions: "[3.0,)"
     ...
    ```
  - [x] `io.quarkus.platform:quarkus-camel-bom`-dependencies must not be `>=3.0.0`
    ```yaml
    ignore:
      ...
      - dependency-name: "io.quarkus.platform:quarkus-camel-bom"
        versions: "[3.0,)"
      ...
    ```
- [x] PR configuration:
  - [x] PRs must be targeted at branch `2.x` 
- [ ] Implementation:
  - [x] The changes must be made on the default- (i.e. `main`-) branch, NOT on the `2.x` branch,
  - [ ] although it will be downstreamed (cherry-picked) for consistency
